const DEFAULT_HEADER = `# Changelog

All notable changes to this project will be documented in this file. Sections
below are generated by [cliff-notes](https://github.com/a2-ai/cliff-notes) —
edits to rewritten entries are fine, but the audit comment block at the end of
each section should be preserved so future runs can re-render.

`;

export interface MergeOptions {
  existing: string | null; // existing CHANGELOG.md contents, or null if not present
  newSection: string; // rendered section (already ends with a newline)
  unreleased: boolean; // if true, replace any existing [Unreleased] block
}

export function mergeChangelog(opts: MergeOptions): string {
  const base = opts.existing ?? DEFAULT_HEADER;
  const headings = locateHeadings(base);

  if (opts.unreleased) {
    const existingUnreleased = headings.find((h) => h.tag === "Unreleased");
    if (existingUnreleased) {
      // Replace from this heading through the start of the next heading.
      const next = headings.find((h) => h.start > existingUnreleased.start);
      const before = base.slice(0, existingUnreleased.start);
      const after = next ? base.slice(next.start) : "";
      return before + ensureTrailingNewline(opts.newSection) + after;
    }
    // No existing Unreleased — fall through to insert-before-first-tag.
  }

  // Insert the new section before the first release heading.
  const firstHeading = headings[0];
  if (!firstHeading) {
    // No existing sections — append after the header preamble.
    return ensureTrailingNewline(base) + ensureTrailingNewline(opts.newSection);
  }
  const before = base.slice(0, firstHeading.start);
  const after = base.slice(firstHeading.start);
  return ensureTrailingNewline(before) + ensureTrailingNewline(opts.newSection) + after;
}

interface Heading {
  start: number; // byte offset of the `#` character starting `## [...`
  tag: string; // the bracketed tag, e.g. "v1.2.3" or "Unreleased"
}

function locateHeadings(s: string): Heading[] {
  const out: Heading[] = [];
  const re = /^## \[([^\]]+)\]/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(s)) !== null) {
    out.push({ start: m.index, tag: m[1]! });
  }
  return out;
}

function ensureTrailingNewline(s: string): string {
  if (s.endsWith("\n\n")) return s;
  if (s.endsWith("\n")) return s + "\n";
  return s + "\n\n";
}
